#debug: true
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.miniapp: DEBUG

wechat:
  miniapp:
    appid: wxb3596b2d855782b7
    secret: 4229d31f90241c2a8f5f40a61a9c10ee
    token: 111
    aesKey: 111
    msgDataFormat: JSON


#spring:
#  datasource:
#    type:  com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=UTF-8
#    data-username: root
#    password: root

spring:
  datasource:
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Fhzd123!@#
    #password: Fhzd123456!@#$%^
    url: jdbc:mysql://120.132.2.244:3306/vote?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://60.191.21.214:1718/lib?characterEncoding=utf-8&useSSL=false
    #username: fhdream
    #password: Fhzd123!@#
    initialize: true
    init-db: true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
#        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
              hibername:
                dailect: org.herbernate.dialect.MySQL5Dialect

  redis:
      database: 0
      host: 127.0.0.1
      password:
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
      timeout: 3600